### ISSUE TITLE
unable to resolve intent: act=android.intent.action.BADGE_COUNT_UPDATE

### ISSUE THREAD

**Issue by chrystoffer** [AppWerft/Ti.Badger#1]
I'm testing on a motorola xt1095 - android 7.1.2 and it shows an error message:

> [WARN]  W/System.err: me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge
[WARN]  W/System.err: 	at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:92)
[WARN]  W/System.err: 	at de.appwerft.badger.BadgerModule.handleSetBadge(BadgerModule.java:55)
[WARN]  W/System.err: 	at de.appwerft.badger.BadgerModule.access$000(BadgerModule.java:25)
[WARN]  W/System.err: 	at de.appwerft.badger.BadgerModule$1.run(BadgerModule.java:47)
[WARN]  W/System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
[WARN]  W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN]  W/System.err: 	at android.os.Looper.loop(Looper.java:154)
[WARN]  W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
[WARN]  W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
[WARN]  W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
[WARN]  W/System.err: Caused by: me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }
[WARN]  W/System.err: 	at me.leolin.shortcutbadger.impl.DefaultBadger.executeBadge(DefaultBadger.java:32)
[WARN]  W/System.err: 	at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:90)

My code:

> var Badger = require("de.appwerft.badger");
	Badger.setBadge(2);
	Badger.getLauncher();

Version: 1.0.3 / SDK 6.1.0

**Comment by chrystoffer** [comment]
I noticed that the launcher does not support badger :(
